### ISSUE TITLE
Lack of Internal Dependency Files from python source project

### ISSUE THREAD

**Issue by JuneLyoo** [0xpayne/gpt-migrate#10]
Hello,

During the project setup, I noticed that a source project does not have any internal dependency files. 

I propose the following solution to generate a list of dependencies for this project:

**Solution Steps:**

1. Use Pipdeptree to generate a list of dependencies.

Install pipdeptree:
```bash
$ pip install pipdeptree
```

2. As an example, let's say we want to generate a dependency tree for a package named 'requests'. Execute the following command:

```bash
$ pipdeptree -p requests
```
This should provide an output similar to the following:

```bash
requests==2.23.0
  - certifi [required: >=2017.4.17, installed: 2020.4.5.1]
  - chardet [required: >=3.0.2,<4, installed: 3.0.4]
  - idna [required: >=2.5,<3, installed: 2.9]
  - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.9]
```

3. Next, copy these dependencies and their version information into a `requirements.txt` file, like so:

```bash
certifi>=2017.4.17
chardet>=3.0.2,<4
idna>=2.5,<3
urllib3>=1.21.1,<1.26,!=1.25.1,!=1.25.0
```

4. Lastly, you can download the dependencies to the current directory without installing them by using the following command:

```bash
(current directory) $ pip download -r requirements.txt
```

This method will allow us make the project set-up smoother for python source projects. Thanks.

original link: https://www.activestate.com/resources/quick-reads/how-to-download-python-dependencies/

**Comment by 0xpayne** [comment]
Added requirements.txt files to each of the benchmarks and added instructions in readme, should be sufficient

https://github.com/0xpayne/gpt-migrate/commit/6ae7cc2497a78893a3cb57344453c58ebf4a6c8c
