### ISSUE TITLE
Rate limit error on Python 3 to PHP

### ISSUE THREAD

**Issue by curtisdelicata** [0xpayne/gpt-migrate#15]
openai.error.RateLimitError: Rate limit reached for default-gpt-3.5-turbo-16k in organization org-xxxxxxxxxxxxxxx on tokens per min. Limit: 180000 / min. Current: 178656 / min. Contact us through our help center at help.openai.com if you continue to have issues.

I don't have gpt-4 trial. It has a lot of lines appearing for same python file. Is it stuck in a loop? I'm trying to port https://github.com/apriha/lineage to PHP 8.2 from Python 3.

Sorry I should of described this in my previous issue that was closed.

**Comment by curtisdelicata** [comment]
Does anyone have GPT 4 that can port it and test? I can pay for the billing at openai.com and time spent.

**Comment by 0xpayne** [comment]
This is due to your OpenAI account unfortunately - [Rate Limits](https://platform.openai.com/account/rate-limits)
