### ISSUE TITLE
The model: `gpt-4-32k` does not exist

### ISSUE THREAD

**Issue by tonyphoang** [0xpayne/gpt-migrate#25]
I have gpt-4 access but when I try to use gpt-4-32k it gives me this error below, thoughts? 
`openai.error.InvalidRequestError: The model: `gpt-4-32k` does not exist`

**Comment by MkuuWaUjinga** [comment]
Access to gpt-4 and gpt-4-32k are rolled out separately. Seems like you don't have access to gpt-4-32k yet

**Comment by mcpengelly** [comment]
for posterity sake. https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4
