### ISSUE TITLE
Target repository doesn't make use of internal functions

### ISSUE THREAD

**Issue by MkuuWaUjinga** [0xpayne/gpt-migrate#26]
Saw this using the benchmark flask-nodejs:

`app.js` is not importing `db.js` but instead uses an external library `node-json-db`: `const db = new JsonDB(new Config("storage/items", true, false, '/'));`.

What about adding the internal function signatures, which the source file depends on, to the migration prompt for the target file? This should probably fix it :) Related to #5.

**Comment by 0xpayne** [comment]
It's non-deterministic unfortunately so I won't have the same errors that you have. If you run it again or let the debugger work it'll likely fix it (eventually). Certainly agreed that #5 will help!

**Comment by MkuuWaUjinga** [comment]
Yeah, I get it roughly every second time I do the migration. Debugging doesn't help as all the generated tests are green. Is somebody already working on #5. Happy to add a PR

**Comment by 0xpayne** [comment]
Please feel free to submit a PR!
