### ISSUE TITLE
Demanding 320k tokens

### ISSUE THREAD

**Issue by Devesh-N** [0xpayne/gpt-migrate#27]
When I gave the command it thought for a long long time and then finally when it gave a response it said 32k tokens was not enough! It demands 320k tokens for my small app which is only 440 MB! Sucks

**Comment by zerofill** [comment]
440MB is a small app? lol

**Comment by 0xpayne** [comment]
Sorry to break it to you but...

440MB is massive 😅

**Comment by Devesh-N** [comment]
> Sorry to break it to you but...
> 
> 440MB is massive 😅

@0xpayne Then what's the point of this if it can't even migrate this app and even uses tokens unnecessarily? I got a 0.02 charge. Also, the 440 I meant all my program files were about 3 MB. The Venv folder from my Jetbrains ide was about 410 MB in size and the size on disk of about 437 MB. So I am not kidding when I said it is a small app of 3 MB! Please re-open this issue @zerofill  @0xpayne

**Comment by Devesh-N** [comment]
Sorry for not clarifying this earlier!

**Comment by 0xpayne** [comment]
Can you share the repo you are trying to migrate? I can have a look.

On cost, it's made clear that you need to be aware of large token requests in the disclaimer and in the readme.

**Comment by Devesh-N** [comment]
> Can you share the repo you are trying to migrate? I can have a look.
> 
> On cost, it's made clear that you need to be aware of large token requests in the disclaimer and in the readme.

@0xpayne The cost is not the problem. It is using tokens unnecessarily. The repo I am migrating is private. I would have shared it but it has apikey, URLs exposed so it will not be a good idea to share it.
