### ISSUE TITLE
Use poetry for installation

### ISSUE THREAD

**Issue by wwzeng1** [0xpayne/gpt-migrate#34]
Happy to help write this using Sweep https://github.com/sweepai/sweep

**Comment by 0xpayne** [comment]
I also think Poetry is the stronger tool but most people use pip so let's keep pip. Feel free to also add instructions for poetry though. You can also use Sweep, love seeing these AI coding tools! @wwzeng1

**Comment by wwzeng1** [comment]
I'll give it a try soon, thanks @0xpayne!

**Comment by wwzeng1** [comment]
@0xpayne got this working!
![image](https://github.com/0xpayne/gpt-migrate/assets/44910023/019d78af-8f58-4fa8-a105-ef2a0b12eb71)

**Comment by wwzeng1** [comment]
Was a fun experience, check out https://github.com/sweepai-dev/gpt-migrate/pull/5 the debug flow.
